In [1]:
import pandas as pd
from src.setup import get_base
from src.feature_engineering import engineer_features

In [2]:
df = get_base()

In [3]:
df_features = engineer_features(df)

In [4]:
display(df_features)
display(df_features.head())

,age,gender,married,has_children,avg_clicks,total_clicks,total_cancellation,avg_session_duration,total_session_duration,total_sessions,avg_flight_discount,total_flight_discount,avg_hotel_discount,total_hotel_discount,total_flights_booked,total_hotels_booked,avg_flight_fare_usd,total_flight_fare_usd,n_unique_destinations
user_id,,,,,,,,,,,,,,,,,,,
23557,66,0.0,1,0,10.250,82,0,1.277083,10.216667,8,0.000,0,0.250,2,0,2,0.000000,0.00,0
94883,53,0.0,1,0,9.125,73,0,1.129167,9.033333,8,0.000,0,0.125,1,2,2,432.045000,864.09,2
101486,52,0.0,1,1,16.375,131,0,2.037500,16.300000,8,0.250,2,0.000,0,1,2,189.910000,189.91,1
101961,45,0.0,1,0,15.750,126,0,1.962500,15.700000,8,0.250,2,0.125,1,5,5,248.532000,1242.66,5
106907,46,0.0,1,1,30.000,240,1,12.648584,101.188675,8,0.125,1,0.125,1,2,2,13902.060000,27804.12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792549,47,0.0,0,0,14.250,114,0,1.781250,14.250000,8,0.125,1,0.000,0,4,1,259.792500,1039.17,4
796032,52,0.0,1,0,18.500,148,1,9.088659,72.709272,8,0.250,2,0.125,1,4,3,1305.410000,5221.64,3
801660,55,0.0,1,1,14.375,115,0,1.766667,14.133333,8,0.375,3,0.000,0,3,3,136.653333,409.96,1
811077,46,0.0,1,1,13.125,105,0,1.652083,13.216667,8,0.250,2,0.125,1,1,1,579.790000,579.79,1
844489,25,1.0,0,1,12.375,99,0,1.552083,12.416667,8,0.125,1,0.125,1,0,0,0.000000,0.00,0

,age,gender,married,has_children,avg_clicks,total_clicks,total_cancellation,avg_session_duration,total_session_duration,total_sessions,avg_flight_discount,total_flight_discount,avg_hotel_discount,total_hotel_discount,total_flights_booked,total_hotels_booked,avg_flight_fare_usd,total_flight_fare_usd,n_unique_destinations
user_id,,,,,,,,,,,,,,,,,,,
23557,66,0.0,1,0,10.250,82,0,1.277083,10.216667,8,0.000,0,0.250,2,0,2,0.000,0.00,0
94883,53,0.0,1,0,9.125,73,0,1.129167,9.033333,8,0.000,0,0.125,1,2,2,432.045,864.09,2
101486,52,0.0,1,1,16.375,131,0,2.037500,16.300000,8,0.250,2,0.000,0,1,2,189.910,189.91,1
101961,45,0.0,1,0,15.750,126,0,1.962500,15.700000,8,0.250,2,0.125,1,5,5,248.532,1242.66,5
106907,46,0.0,1,1,30.000,240,1,12.648584,101.188675,8,0.125,1,0.125,1,2,2,13902.060,27804.12,1