In [1]:
import pandas as pd
from src.setup import get_base
from src.feature_engineering import engineer_features

In [2]:
df = get_base()

In [3]:
df

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,...,trip_airline,destination_airport_lat,destination_airport_lon,base_fare_usd,hotel_name,nights,rooms,check_in_time,check_out_time,hotel_price_per_room_night_usd
0,101486-6d053e0f51884dddb339416c86d5b3a9,101486,NaN,2023-07-18 09:35:00,2023-07-18 09:35:22,False,False,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN
1,101486-6de2ac91a8c24619a69a3d3ae7c28d61,101486,NaN,2023-03-21 10:16:00,2023-03-21 10:18:38,False,False,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN
2,101486-7e8b450e5fe94345bd6c1ae9f479f073,101486,NaN,2023-02-11 17:05:00,2023-02-11 17:07:58,False,False,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN
3,101486-9e7d5ccc7e034bf7b7a5ad2f3befbe13,101486,NaN,2023-05-30 20:42:00,2023-05-30 20:44:15,True,False,0.1,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN
4,101486-be6d02b11839441aa4107044d095cb99,101486,NaN,2023-03-06 21:50:00,2023-03-06 21:50:53,False,False,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49099,94883-a7021e0950814faa8fb9045613065658,94883,NaN,2023-01-19 20:06:00,2023-01-19 20:06:44,False,False,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN
49100,94883-b74774da212f4ceea8647085ca2f4a30,94883,94883-bcc118ad37024c4ab14c62d46daf2ac0,2023-04-10 21:13:00,2023-04-10 21:16:16,False,False,NaN,NaN,True,...,Delta Air Lines,30.494,-81.688,623.17,Four Seasons - jacksonville,0.0,2.0,2023-04-16 13:55:13.980,2023-04-17 11:00:00,50.0
49101,94883-d6ab30bec3474af684c9af4d299bfc2d,94883,94883-6df625fce4364de499e99b0e608322e7,2023-03-18 12:24:00,2023-03-18 12:26:40,False,False,NaN,NaN,True,...,United Airlines,43.862,-79.370,240.92,Hilton - toronto,1.0,1.0,2023-03-27 10:42:49.050,2023-03-28 11:00:00,130.0
49102,94883-ec6cc8bb0a7441739923714e2f75bceb,94883,NaN,2023-01-10 12:20:00,2023-01-10 12:20:14,False,False,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN
49103,94883-f649e048680a4119afc2ef90eec3c7f0,94883,NaN,2023-01-26 22:25:00,2023-01-26 22:25:16,False,False,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN

In [4]:
df_features = engineer_features(df)

In [5]:
display(df_features)
display(df_features.head())

,age,gender,married,has_children,avg_clicks,total_clicks,total_cancellation,avg_session_duration,total_session_duration,total_sessions,...,total_flight_discount,avg_hotel_discount,total_hotel_discount,total_flights_booked,total_hotels_booked,avg_flight_fare_usd,total_flight_fare_usd,n_unique_destinations,total_people,avg_people
user_id,,,,,,,,,,,,,,,,,,,,,
23557,66,0.0,1,0,10.250,82,0,1.277083,10.216667,8,...,0,0.250,2,0,2,0.000000,0.00,0,3.0,0.375
94883,53,0.0,1,0,9.125,73,0,1.129167,9.033333,8,...,0,0.125,1,2,2,432.045000,864.09,2,3.0,0.375
101486,52,0.0,1,1,16.375,131,0,2.037500,16.300000,8,...,2,0.000,0,1,2,189.910000,189.91,1,3.0,0.375
101961,45,0.0,1,0,15.750,126,0,1.962500,15.700000,8,...,2,0.125,1,5,5,248.532000,1242.66,5,5.0,0.625
106907,46,0.0,1,1,30.000,240,1,12.648584,101.188675,8,...,1,0.125,1,2,2,13902.060000,27804.12,1,12.0,1.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792549,47,0.0,0,0,14.250,114,0,1.781250,14.250000,8,...,1,0.000,0,4,1,259.792500,1039.17,4,4.0,0.500
796032,52,0.0,1,0,18.500,148,1,9.088659,72.709272,8,...,2,0.125,1,4,3,1305.410000,5221.64,3,6.0,0.750
801660,55,0.0,1,1,14.375,115,0,1.766667,14.133333,8,...,3,0.000,0,3,3,136.653333,409.96,1,3.0,0.375
811077,46,0.0,1,1,13.125,105,0,1.652083,13.216667,8,...,2,0.125,1,1,1,579.790000,579.79,1,1.0,0.125
844489,25,1.0,0,1,12.375,99,0,1.552083,12.416667,8,...,1,0.125,1,0,0,0.000000,0.00,0,0.0,0.000

,age,gender,married,has_children,avg_clicks,total_clicks,total_cancellation,avg_session_duration,total_session_duration,total_sessions,...,total_flight_discount,avg_hotel_discount,total_hotel_discount,total_flights_booked,total_hotels_booked,avg_flight_fare_usd,total_flight_fare_usd,n_unique_destinations,total_people,avg_people
user_id,,,,,,,,,,,,,,,,,,,,,
23557,66,0.0,1,0,10.250,82,0,1.277083,10.216667,8,...,0,0.250,2,0,2,0.000,0.00,0,3.0,0.375
94883,53,0.0,1,0,9.125,73,0,1.129167,9.033333,8,...,0,0.125,1,2,2,432.045,864.09,2,3.0,0.375
101486,52,0.0,1,1,16.375,131,0,2.037500,16.300000,8,...,2,0.000,0,1,2,189.910,189.91,1,3.0,0.375
101961,45,0.0,1,0,15.750,126,0,1.962500,15.700000,8,...,2,0.125,1,5,5,248.532,1242.66,5,5.0,0.625
106907,46,0.0,1,1,30.000,240,1,12.648584,101.188675,8,...,1,0.125,1,2,2,13902.060,27804.12,1,12.0,1.500

In [7]:
df_features['total_people'].unique()

array([ 3.,  5., 12.,  8.,  1.,  4.,  6.,  0.,  2., 10.,  7., 11.,  9.,
       14., 15., 13., 17., 16.])